//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.30 at 07:47:34 PM JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sbml.org/sbml/level2/version4", xmlns = { @XmlNs(namespaceURI = "http://www.sbml.org/2001/ns/celldesigner", prefix="celldesigner"), @XmlNs(namespaceURI = "http://www.w3.org/1998/Math/MathML", prefix="mathml"), @XmlNs(namespaceURI = "http://www.sbml.org/sbml/level2/version4", prefix="")},elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sbml.sbml.level2.version4;
import javax.xml.bind.annotation.XmlNs;

